-- SQL Update for GestSup !!! If you are not in lastest version, all previous scripts must be passed before !!! ;
SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET default_storage_engine=INNODB;

-- update GestSup version number
UPDATE `tparameters` SET `version`='3.2.54';

ALTER DATABASE CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tincidents CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tagencies CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tassets CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tassets_iface CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tassets_iface_role CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tassets_location CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tassets_manufacturer CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tassets_model CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tassets_network CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tassets_state CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tassets_thread CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tassets_type CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tattachments CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tauth_attempts CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tcategory CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tcompany CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tcriticality CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tentra_tenant CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tevents CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tgroups CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tgroups_assoc CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tincidents CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tlogs CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tmails CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tparameters CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tparameters_imap_multi_mailbox CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tparameters_user_validation_exclusion CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tplaces	CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tplugins CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tpriority CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tprocedures CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tprofiles CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tprojects CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tprojects_task CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE trights CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tservices CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tstates CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tsubcat CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tsurvey_answers CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tsurvey_questions CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE ttemplates CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tthreads CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE ttime CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE ttoken CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE ttypes CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE ttypes_answer CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tusers CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tusers_agencies CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tusers_ip CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tusers_services CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tusers_tech CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;
ALTER TABLE tviews CONVERT TO CHARACTER SET utf8 COLLATE utf8mb3_general_ci;